### PR TITLE
fix radar endpoint

### LINKED ISSUE #36: broken due to api changes on flightradar site
may related to #35 

the used endpoint https://data-live.flightradar24.com/zones/fcgi/feed.js (in `radar.js`) is now redirected to https://www.flightradar24.com/static/legacy/feed.json so this module does'nt work anymore.

Did not dig into the website if the new url is usable (may with changed parameters).

At the moment the other endpoint https://data-cloud.flightradar24.com/zones/fcgi/feed.js is still working so a quick fix would be to replace this ...

### PR DESCRIPTION
**Pull request by khassel**
old url doesn't work anymore

fixes: #36

### CODE REVIEW

**Comment by derhuerst** [comment]
Thanks!

**Comment by derhuerst** [comment]
Do you want to be mentioned in [`contributors`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#people-fields-author-contributors)? If you do, using which notation?

**Comment by khassel** [comment]
thanks, not necessary ...

**Comment by derhuerst** [comment]
Published as `flightradar24-client@1.0.1`. 🎉

**Pull request merged**
